### ISSUE TITLE
How to set .html files to Spacebar file type by default?

### ISSUE THREAD

**Issue by tsega** [tamino-martinius/atom-language-spacebars#1]
@Zaku-eu first of all, great plugin!

Second I'm a [Meteor](http://meteor.com/) developer and I want to have a project setting that will map all JavaScript files to [JavaScript (Meteor)](https://atom.io/packages/meteor-api) and all HTML files to Spacebars.

Any suggestions on how to do that?

**Comment by Billybobbonnet** [comment]
:+1:  I would like to use the snippets in html.

**Comment by fungilation** [comment]
From Atom 1.0.8 changelog:
`Added a setting, core.customFileTypes, for configuring the association between file names and grammars.`

I'm not sure how to use this new config to associate .html with Spacebar?

**Comment by derwaldgeist** [comment]
+1

Also for me, this is the most-wanted feature. If I add a new file or rename an existing one, it reverts to HTML, which means that the block helpers like {{#if}} do not indent any more. I am using Atom for Meteor exclusively, so I would love to switch .html to Spacebars as the default language grammar.

According to the docs, it should work if I add this to my config.cson file:

``` cson
"*":
  core:
    customFileTypes:
      "source.spacebars.embedded.html": [
        "html"
      ]
```

But it still defaults to HTML instead of Spacebars. I've got the `source.spacebars.embedded.html` tag from the source code of the plugin, maybe this is wrong?

See also: https://github.com/atom/atom/issues/1718

**Comment by ryanple** [comment]
Just in case anyone else hits this snag and stumbles across this, I followed @derwaldgeist 's link to Atom Issue #1718 and followed one of the recommendations:

```
"*":
  core:
    customFileTypes:
      "text.html.spacebars": [
        "html"
      ] ...
```

Seems to be working fine when getting inside html files now using Spacebars as the syntax language.

**Comment by tamino-martinius** [comment]
Thanks for @derwaldgeist for figuring this out, but this should now be handled correctly by Atom and Spacebars should be auto detected as language. If nothing helps this is the current workaround since Atom 1.4

```
core:
  customFileTypes:
    "text.html.spacebars": [
      "html"
    ]
```
